In [1]:
#import !


import numpy as np

import sys

from gym.envs.toy_text import discrete

In [2]:

UP = 0

RIGHT = 1

DOWN = 2

LEFT= 3




#### gym environment git!


https://github.com/openai/gym/tree/master/gym/envs/toy_text




In [9]:

shape=[4,4]

np.shape(shape)


(2,)

In [10]:
if not isinstance(shape, (list,tuple)) or not len(shape) == 2:
    raise ValueError('데이터의 길이가 2이어야 합니다')
    

In [41]:
#2

print(shape[0])


print(shape[1])

4
4


In [42]:
np.prod(shape)

16

In [43]:
#3

np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
#4

grid = np.arange(16).reshape(4,4)


print(grid)

print("-"*100)

print("apply np.nditer??")


print(np.nditer(grid))
    
    


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------------------------------------------------------------------------------------------
apply np.nditer??


In [45]:
np.arange(100).reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [46]:
#이 때, ndarray는 N x M 사이즈 행렬로 이루어진 경우에 np.nditer(변수) 를 통하여 한 원소씩 접근 가능합니다.

import numpy as np




for x in np.nditer(np.arange(100).reshape(20,5)):
    print(x)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [47]:


print("After apply nditer!!")


for i in np.nditer(grid, flags = ['multi_index']):
    print(i)

After apply nditer!!
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [48]:
#4
grid = np.arange(16).reshape(4,4)

it =np.nditer(grid, flags = ['multi_index'])


In [49]:
P ={}

nS = np.prod(shape)



MAX_Y = shape[0]
MAX_X = shape[1]

        
        

In [50]:
P

{}

In [52]:
{a : [] for a in range(4)}  

    

{0: [], 1: [], 2: [], 3: []}

In [ ]:
# lambda?

lam =lambda x : x + 1
 
def lamd(x):
    return x + 1



In [54]:
is_done = lambda s:s ==0 or s== (nS-1)


In [58]:
def state(s):
    if s==0:
        return True
    elif s==15:
        return True
    else:
        return False

In [59]:
for i in range(16):
    state(i)
    print(i,state(i))

0 True
1 False
2 False
3 False
4 False
5 False
6 False
7 False
8 False
9 False
10 False
11 False
12 False
13 False
14 False
15 True


In [60]:


for i in range(16):
    
    print("s가",i,"일때", is_done(s=i))


s가 0 일때 True
s가 1 일때 False
s가 2 일때 False
s가 3 일때 False
s가 4 일때 False
s가 5 일때 False
s가 6 일때 False
s가 7 일때 False
s가 8 일때 False
s가 9 일때 False
s가 10 일때 False
s가 11 일때 False
s가 12 일때 False
s가 13 일때 False
s가 14 일때 False
s가 15 일때 True


In [61]:
if 2==1:
    print("true")
else:
    print("false")


false


In [73]:
a = 15

x=1

while not x==15:
    print(x)
    x+=1
    


1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [13]:

#uniform

isd = np.ones(4) / 4

print(isd)

[ 1.  1.  1.  1.]


#super function explain

http://bluese05.tistory.com/5

In [75]:
mode = 'human'
outfile = StringIO() if mode == 'ansi' else sys.stdout

print(outfile)

stringIO example

https://docs.python.org/2/library/stringio.html

In [ ]:
grid = np.arange(nS).reshape(shape)

it = np.nditer(grid, flags = ['multi_index'])


In [ ]:
def _render(self, mode = 'human', close = False):
    


    while not it.finished:
        s = it.iterindex
        y,x = it.multi_index
    
        if self.s == s:
            output = "x"
        elif s == 0 or s==self.nS - 1:
            output = "T"
        else:
            output = "o"
    
        if x ==0:
            output = output.lstrip()
        if x==self.shape[1] - 1:
            output= output.rstrip()
    
        outfile.write(output)
    
        if x == self.shape[1]-1:
            outfile.write("\n")
        
        it.iternext()

Example of lstrip

https://www.tutorialspoint.com/python/string_lstrip.htm


Example of rstrip

https://www.tutorialspoint.com/python/string_rstrip.htm
