# This is a Pytorch Tutorial



In [1]:
import torch
import numpy as np


# Tensor???




![alt text](01.jpg "pytorch?")

![alt text](сДЙсЕ│сЖпсДЕсЕбсДЛсЕ╡сДГсЕ│02.jpg "pytorch??")

In [16]:
print("replacement for numpy to use the power of GPU")
print("deep learning research platform that provides maximum flexibility and speed")

replacement for numpy to use the power of GPU
deep learning research platform that provides maximum flexibility and speed


![alt text](сДЙсЕ│сЖпсДЕсЕбсДЛсЕ╡сДГсЕ│03.jpg "pytorch??")

In [17]:
import numpy as np

example_numpy= np.array([[5,2],[2,5]])
print(example_numpy)

[[5 2]
 [2 5]]


# Construct Matrix 


![alt text](сДЙсЕ│сЖпсДЕсЕбсДЛсЕ╡сДГсЕ│04.jpg "pytorch??")


In [18]:

#Uninitialize 
Un_mat=torch.Tensor(5,3)

Un_mat2=torch.Tensor(4,8)


print(Un_mat)
print(Un_mat2)




 1.4213e+08  4.5750e-41  1.4213e+08
 4.5750e-41         nan  4.5750e-41
 1.2497e+04  1.1405e+04  6.4101e-10
 4.3199e-05  1.8460e-07  7.0478e+02
 6.7137e-07  1.6881e-07  1.0242e-11
[torch.FloatTensor of size 5x3]



Columns 0 to 5 
 1.4213e+08  4.5750e-41  1.4213e+08  4.5750e-41  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.7937e-43  0.0000e+00

Columns 6 to 7 
 0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00
 4.4842e-44  0.0000e+00
[torch.FloatTensor of size 4x8]



![alt text](сДЙсЕ│сЖпсДЕсЕбсДЛсЕ╡сДГсЕ│05.jpg "pytorch??")

In [19]:
#Randomly Initiailzied Matrix

In_mat=torch.randn(5,3)
In_mat2=torch.randn(4,8)
print(In_mat)
print(In_mat2)


-0.1100 -0.0738  0.2871
-0.1532  1.6134  1.4124
 0.1476 -0.4961  0.9236
 1.5267 -0.2079 -0.3273
-0.6666  0.1977 -0.9329
[torch.FloatTensor of size 5x3]


 0.8324  1.5777  0.3075  0.9543  1.3557  0.5196  0.5296  1.5105
-0.7143  0.3981 -0.1586  0.2449 -1.7162  1.3048 -1.2818  0.3597
-0.8930 -0.6277 -0.9585 -0.4735 -1.2230  0.0412  1.1653  1.1330
-0.4476 -0.1679  0.2518  0.7881  0.3342 -1.5632 -0.6251 -0.8035
[torch.FloatTensor of size 4x8]




# Operations 

![alt text](сДЙсЕ│сЖпсДЕсЕбсДЛсЕ╡сДГсЕ│06.jpg "pytorch??")

In [20]:
a=torch.rand(5,2)

In [21]:
b=torch.rand(5,2)

In [22]:
print(a)
print(b)
print(a+b)

torch.add(a,b)


 0.8049  0.6703
 0.8113  0.7226
 0.7606  0.3078
 0.7203  0.4332
 0.9442  0.5564
[torch.FloatTensor of size 5x2]


 0.3009  0.0479
 0.8680  0.8975
 0.5720  0.7647
 0.3391  0.5130
 0.2630  0.3400
[torch.FloatTensor of size 5x2]


 1.1058  0.7181
 1.6793  1.6201
 1.3326  1.0725
 1.0594  0.9462
 1.2072  0.8964
[torch.FloatTensor of size 5x2]




 1.1058  0.7181
 1.6793  1.6201
 1.3326  1.0725
 1.0594  0.9462
 1.2072  0.8964
[torch.FloatTensor of size 5x2]

### giving an output tensor

In [1]:
result=torch.Tensor(5,3)
out=torch.add(a,b,out=result)
print(out)
print(result)

NameError: name 'torch' is not defined

In [24]:
a


 0.8049  0.6703
 0.8113  0.7226
 0.7606  0.3078
 0.7203  0.4332
 0.9442  0.5564
[torch.FloatTensor of size 5x2]

In [25]:
print(a[:,1])


 0.6703
 0.7226
 0.3078
 0.4332
 0.5564
[torch.FloatTensor of size 5]



In [26]:
b=torch.ones(5)
print(b)
a
c=b.numpy()
d=a.numpy()
a

d





 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



array([[ 0.80489326,  0.67027372],
       [ 0.81131333,  0.7226119 ],
       [ 0.76056987,  0.30776983],
       [ 0.7203269 ,  0.43321446],
       [ 0.94421947,  0.55636609]], dtype=float32)

# numpy bridge

![alt text](сДЙсЕ│сЖпсДЕсЕбсДЛсЕ╡сДГсЕ│07.jpg "pytorch??")

In [27]:

# torch to numpy

torch_to_numpy= torch.rand(5,3)

print(torch_to_numpy)

torch_to_numpy.numpy()


 0.4430  0.4126  0.3118
 0.0324  0.3998  0.2025
 0.2731  0.3058  0.0672
 0.6814  0.7165  0.8389
 0.2186  0.5120  0.5133
[torch.FloatTensor of size 5x3]



array([[ 0.4429709 ,  0.41257447,  0.31180006],
       [ 0.03236676,  0.39978251,  0.20245542],
       [ 0.27309191,  0.30579886,  0.06719829],
       [ 0.68137193,  0.71646774,  0.83889329],
       [ 0.21864745,  0.51197046,  0.51333851]], dtype=float32)

![alt text](сДЙсЕ│сЖпсДЕсЕбсДЛсЕ╡сДГсЕ│08.jpg "pytorch??")

In [28]:
# numpy to torch
numpy_to_torch=np.ones(5)

print(numpy_to_torch)

print(torch.from_numpy(numpy_to_torch))




[ 1.  1.  1.  1.  1.]

 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

