Basic Numpy

In [1]:
import numpy as np

In [3]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [4]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [6]:
print(np.eye(2))

print(np.eye(4))

[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [11]:

data1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
data1.shape

(3, 3)

In [14]:
data1.dtype

dtype('int32')

In [18]:
num_str=np.array(['1.25','0.99','44','11'])
print(num_str)

num_str=np.array(['1.25','0.99','44','11'],dtype=np.string_)
print(num_str)

['1.25' '0.99' '44' '11']
[b'1.25' b'0.99' b'44' b'11']


In [19]:
num_str.astype("float")

array([  1.25,   0.99,  44.  ,  11.  ])

In [25]:
print(data1)

print(data1*data1)
print(data1+3)
print(data1/2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 0.5  1.   1.5]
 [ 2.   2.5  3. ]
 [ 3.5  4.   4.5]]


In [26]:
data1-data1/3

array([[ 0.66666667,  1.33333333,  2.        ],
       [ 2.66666667,  3.33333333,  4.        ],
       [ 4.66666667,  5.33333333,  6.        ]])

In [27]:
1/data1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667],
       [ 0.14285714,  0.125     ,  0.11111111]])

In [28]:
print(data1**2)
print(data1**0.5)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1.          1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974]
 [ 2.64575131  2.82842712  3.        ]]


In [39]:
print(np.array(10))

data2=np.arange(10)
print(data2)

10
[0 1 2 3 4 5 6 7 8 9]


In [40]:
data2[0]

0

In [41]:
print(data2)
print(data2[1:4])
data2[1:4]=10
data2

[0 1 2 3 4 5 6 7 8 9]
[1 2 3]


array([ 0, 10, 10, 10,  4,  5,  6,  7,  8,  9])

In [43]:
#becareful that copy changes original
tmp=data2[1:4]
print(tmp)
print(tmp[1])
tmp[1]=20
print(tmp)
print(data2)

[10 20 10]
20
[10 20 10]
[ 0 10 20 10  4  5  6  7  8  9]


In [51]:

print(data1)
print(data1[:2,:2])
print("change 2x2 to zero")
data1[:2,:2]=0
print(data1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
change 2x2 to zero
[[0 0 3]
 [0 0 6]
 [7 8 9]]


In [53]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [58]:
#making random number 7x4
dataNames=np.random.randn(7,4)
dataNames


array([[ 0.63159033,  0.84301268,  0.07223111, -0.28035473],
       [ 0.01319116,  0.50951722, -0.56829051, -1.41089049],
       [ 0.36718264,  0.44665023,  2.98991474,  0.1453201 ],
       [-1.82187386, -0.71426699,  0.11082713, -0.27930028],
       [-2.02812729,  0.78981034,  1.54357127,  1.63801625],
       [ 1.21634105, -0.64159838,  1.45080742,  0.20141173],
       [-1.17849033, -0.8490539 ,  0.79736651, -0.8399333 ]])

In [64]:
names=="Bob"

array([ True, False, False,  True, False, False, False], dtype=bool)

In [71]:
dataNames[names=="Bob"]

array([[ 0.63159033,  0.84301268,  0.07223111, -0.28035473],
       [-1.82187386, -0.71426699,  0.11082713, -0.27930028]])

In [74]:
dataNames[-(names=="Bob")]


c:\users\owner\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  """Entry point for launching an IPython kernel.


array([[ 0.01319116,  0.50951722, -0.56829051, -1.41089049],
       [ 0.36718264,  0.44665023,  2.98991474,  0.1453201 ],
       [-2.02812729,  0.78981034,  1.54357127,  1.63801625],
       [ 1.21634105, -0.64159838,  1.45080742,  0.20141173],
       [-1.17849033, -0.8490539 ,  0.79736651, -0.8399333 ]])

In [80]:
print(names)
mask =( names=="Bob")|(names=="Will")
print(mask)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[ True False  True  True  True False False]


In [81]:
dataNames[mask]

array([[ 0.63159033,  0.84301268,  0.07223111, -0.28035473],
       [ 0.36718264,  0.44665023,  2.98991474,  0.1453201 ],
       [-1.82187386, -0.71426699,  0.11082713, -0.27930028],
       [-2.02812729,  0.78981034,  1.54357127,  1.63801625]])

In [85]:
print(dataNames[dataNames<0]) 
dataNames[dataNames<0]=0
print("After make it to zero", dataNames)

[]
After make it to zero [[ 0.63159033  0.84301268  0.07223111  0.        ]
 [ 0.01319116  0.50951722  0.          0.        ]
 [ 0.36718264  0.44665023  2.98991474  0.1453201 ]
 [ 0.          0.          0.11082713  0.        ]
 [ 0.          0.78981034  1.54357127  1.63801625]
 [ 1.21634105  0.          1.45080742  0.20141173]
 [ 0.          0.          0.79736651  0.        ]]
